FROM mysql:5.7

ENV MYSQL_USER="root" \
    MYSQL_PASSWORD="" \
    MYSQL_ROOT_PASSWORD="" \
    MYSQL_ALLOW_EMPTY_PASSWORD="true" \
    MYSQL_DATABASE="go_product"

RUN touch /var/log/mysql/mysqld.log